In [1]:
import pandas as pd
import geopandas as gpd
from pathlib import Path

In [2]:
project_root = Path.cwd()
if not Path('data').exists():
    project_root = project_root.parent 
print(project_root)

d:\Wu\2026\Project Portfolio\003 Project\grocery-demand-estimation

In [3]:
# data path
tract_path = project_root / 'data/raw/tract_2024/cb_2024_16_tract_500k.shp'
city_path = project_root / 'data/raw/place/cb_2025_16_place_500k.shp'
expenditure_path = project_root / 'data/processed/avg_expenditure_by_income.csv'
demography_path = project_root / 'data/processed/kootenai_demographics2024.csv'

In [4]:
# Read all datasets
tract = gpd.read_file(tract_path)
city = gpd.read_file(city_path)
expend = pd.read_csv(expenditure_path)
demo = pd.read_csv(demography_path)

In [5]:
print(tract.shape)
tract.head()

(456, 14)

,STATEFP,COUNTYFP,TRACTCE,GEOIDFQ,GEOID,NAME,NAMELSAD,STUSPS,NAMELSADCO,STATE_NAME,LSAD,ALAND,AWATER,geometry
0,16,017,950100,1400000US16017950100,16017950100,9501,Census Tract 9501,ID,Bonner County,Idaho,CT,1040606721,159680574,"POLYGON ((-116.50511 47.94953, -116.50481 47.9..."
1,16,059,970200,1400000US16059970200,16059970200,9702,Census Tract 9702,ID,Lemhi County,Idaho,CT,1230047586,1802039,"POLYGON ((-113.99543 45.41691, -113.9945 45.42..."
2,16,083,000300,1400000US16083000300,16083000300,3,Census Tract 3,ID,Twin Falls County,Idaho,CT,381182424,2847873,"POLYGON ((-114.95143 42.53916, -114.9495 42.54..."
3,16,039,960500,1400000US16039960500,16039960500,9605,Census Tract 9605,ID,Elmore County,Idaho,CT,25833164,92328,"POLYGON ((-115.89592 43.07025, -115.88581 43.0..."
4,16,001,010501,1400000US16001010501,16001010501,105.01,Census Tract 105.01,ID,Ada County,Idaho,CT,1022415884,5451232,"POLYGON ((-116.51362 43.38654, -116.51353 43.4..."

In [6]:
print(city.shape)
city.head()

(236, 13)

,STATEFP,PLACEFP,PLACENS,GEOIDFQ,GEOID,NAME,NAMELSAD,STUSPS,STATE_NAME,LSAD,ALAND,AWATER,geometry
0,16,34930,02410697,1600000US1634930,1634930,Hansen,Hansen city,ID,Idaho,25,903899,0,"POLYGON ((-114.30594 42.53688, -114.29864 42.5..."
1,16,39070,02410802,1600000US1639070,1639070,Huetter,Huetter city,ID,Idaho,25,117471,0,"POLYGON ((-116.85411 47.70502, -116.85161 47.7..."
2,16,27460,02410495,1600000US1627460,1627460,Ferdinand,Ferdinand city,ID,Idaho,25,452353,0,"POLYGON ((-116.39491 46.15449, -116.38965 46.1..."
3,16,67870,02410949,1600000US1667870,1667870,Riggins,Riggins city,ID,Idaho,25,1029902,123855,"POLYGON ((-116.32982 45.4122, -116.32138 45.41..."
4,16,16750,02410187,1600000US1616750,1616750,Coeur d'Alene,Coeur d'Alene city,ID,Idaho,25,43691994,1976736,"POLYGON ((-116.85288 47.70099, -116.85096 47.7..."

In [7]:
print(expend.shape)
expend.head()

(6, 9)

,Unnamed: 0,num_cu,pct_cu,income_mean,grocery,grocery_pct,grocery_group,avg_grocery,highest_income
0,Aggregate,135760.0,100.0,104207.0,842257.0,100.0,842257.000,6204.014437,9999999
1,lowest20pct,27139.0,20.0,16658.0,12.3,12.3,103597.611,3817.296547,29932
2,second20pct,27186.0,20.0,42925.0,15.9,15.9,133918.863,4926.023063,57452
3,third20pct,26959.0,19.9,74474.0,18.7,18.7,157502.059,5842.281205,94511
4,fourth20pct,27205.0,20.0,121548.0,23.0,23.0,193719.110,7120.717148,155925

In [8]:
print(demo.shape)
demo.head()

(39, 10)

,GEOID,state,county,tract,household_count,avg_household_size,median_income,median_age,owner_rate,college_plus_pct
0,16055000101,16,55,101,1202,2.59,97381,51.3,88.019967,35.781383
1,16055000102,16,55,102,1847,2.56,96493,49.5,89.767190,23.312883
2,16055000201,16,55,201,1330,2.92,109726,37.8,80.075188,26.440922
3,16055000202,16,55,202,1312,2.70,92500,53.7,96.493902,30.707457
4,16055000203,16,55,203,1407,2.41,70843,52.6,80.739161,26.635146